defaults:
  - trainer: trainer_pl
  - optimizer: adamw
  - scheduler: cosine_annealing
  - dataloader: dataloader
  - dataframe: tile-0.25-2048-256
  - _self_

model:
  entrypoint: TimmBasicModel
  backbone: convnext_xxlarge.clip_laion2b_soup_ft_in1k
  pretrained: True
  num_classes: 5

augmentations:
  train:
    name: get_train_transforms
    img_size: ${img_size}
    flip:  True
    blur: True
    dropout: True
  valid:
    name: get_valid_transforms
    img_size: ${img_size}

seed: 42
name: ${model.backbone}
output_dir:  ../checkpoints/${name}
img_size: 256
fold: 0
checkpoint_id: Null
monitor: val/global/bac
batch_size: 4
num_workers: 6

lr: 2e-5
max_steps: 10000
max_epochs: 10
accumulate_grad_batches: 16
