defaults:
  - trainer: trainer_pl
  - optimizer: adam
  - scheduler: cosine_annealing
  - dataloader: dataloader
  - dataframe: tile-0.25-2048-256
  - _self_

model:
  entrypoint: TimmBasicModel
  backbone: convnext_small.fb_in22k_ft_in1k_384
  pretrained: True
  num_classes: 5
  use_weights: True

augmentations:
  train:
    name: get_train_transforms
    img_size: ${img_size}
    flip:  True
    blur: True
    dropout: True
  valid:
    name: get_valid_transforms
    img_size: ${img_size}

seed: 42
name: ${model.backbone}
output_dir:  ../checkpoints/${name}
img_size: 256
fold: 0
checkpoint_id: Null
monitor: val/global/bac
batch_size: 64
num_workers: 6

lr: 2e-5
max_steps: Null
max_epochs: 6
accumulate_grad_batches: 2
