defaults:
  - trainer: trainer_pl
  - optimizer: adam
  - scheduler: cosine_annealing
  - dataloader: dataloader
  - _self_

model:
  entrypoint: TimmModel
  backbone: tf_efficientnet_b4_ns
  pretrained: True
  num_classes: 5

dataset:
  path: ../input/UBC-OCEAN-PROCESSED/resized-2048-crops/train.parquet
  artifact_name: train-tile-0.25-2048-512.parquet

augmentations:
  train:
    img_size: ${img_size}
    flip:  True
    blur: True
    dropout: True
  valid:
    img_size: ${img_size}

seed: 42
name: ${model.backbone}
output_dir:  ../checkpoints/${name}
img_size: 512
fold: 0
checkpoint_id: Null
monitor: val/MulticlassAccuracy
batch_size: 8
num_workers: 6

lr: 5e-4
max_steps: Null
max_epochs: 50
accumulate_grad_batches: 1
