defaults:
  - trainer: trainer_pl
  - optimizer: adamw
  - scheduler: hf_cosine_with_restarts
  - dataloader: dataloaderp
  - _self_

model:
  entrypoint: TimmModel
  backbone: tf_efficientnetv2_s_in21ft1k
  pretrained: True
  num_classes: 5

dataset:
  path: ../input/UBC-OCEAN-PROCESSED/resized-2048-crops/train.parquet

augmentations:
  train:
    img_size: ${img_size}
    flip:  True
  valid:
    img_size: ${img_size}

seed: 42
name: ${model.backbone}
output_dir:  ../checkpoints/${name}
img_size: 2048
fold: 0
checkpoint_id: ui2ld6af
monitor: val/MulticlassAccuracy
batch_size: 2
num_workers: 12

lr: 5e-4
max_steps: 10000
max_epochs: 50