defaults:
  - trainer: trainer_pl
  - optimizer: adamw
  - scheduler: hf_cosine_with_restarts
  - dataloader: dataloader
  - _self_

model:
  entrypoint: TimmModel
  backbone: tf_efficientnet_b0_ns
  pretrained: True
  num_classes: 5

dataset:
  name: train-MT-None_SS-512_RF-0.5

augmentations:
  train:
    img_size: ${img_size}
    flip:  True
  valid:
    img_size: ${img_size}

seed: 42
name: ${model.backbone}
output_dir:  ../checkpoints/${name}
img_size: 512
fold: 0
monitor: val/MulticlassAccuracy
batch_size: 16
num_workers: 12

lr: 5e-4
max_steps: 10000
max_epochs: 50