defaults:
  - trainer: trainer_pl
  - optimizer: adam
  - scheduler: cosine_annealing
  - dataloader: dataloader
  - dataset: tile-0.25-2048-512
  - _self_

model:
  entrypoint: TimmModel
  backbone: tf_efficientnet_b7.ns_jft_in1k
  pretrained: True
  num_classes: 5
  use_weights: True

augmentations:
  train:
    name: get_train_transforms
    img_size: ${img_size}
    flip:  True
    blur: True
    dropout: True
  valid:
    name: get_valid_transforms
    img_size: ${img_size}

seed: 42
name: ${model.backbone}
output_dir:  ../checkpoints/${name}
img_size: 512
fold: 0
checkpoint_id: b10jsmwb
monitor: val/global/bac
batch_size: 32
num_workers: 6

lr: 2e-5
max_steps: Null
max_epochs: 20
accumulate_grad_batches: 1
