defaults:
  - trainer: trainer_pl
  - optimizer: adam
  - scheduler: cosine_annealing
  - dataloader: dataloader
  - dataset: crop-0.0-2048
  - _self_

model:
  entrypoint: TimmModel
  backbone: tf_efficientnet_b0_ns
  pretrained: True
  num_classes: 5

augmentations:
  train:
    img_size: ${img_size}
    flip:  True
    blur: True
    dropout: True
  valid:
    img_size: ${img_size}

seed: 42
name: ${model.backbone}
output_dir:  ../checkpoints/${name}
img_size: 2048
fold: 0
checkpoint_id: 3kqnxlhm
monitor: val/global/bac
batch_size: 4
num_workers: 6

lr: 2e-5
max_steps: 10000
max_epochs: 25
accumulate_grad_batches: 1
