defaults:
  - trainer: trainer_pl
  - optimizer: adam
  - scheduler: cosine_annealing
  - dataloader: dataloader
  - _self_

model:
  entrypoint: TimmModel
  backbone: tf_efficientnet_b0_ns
  pretrained: True
  num_classes: 5

dataset:
  path: ../input/UBC-OCEAN-PROCESSED/resized-2048-crops/train.parquet

augmentations:
  train:
    img_size: ${img_size}
    flip:  True
    blur: True
    dropout: True
  valid:
    img_size: ${img_size}


name: ${model.backbone}
output_dir:  ../checkpoints/${name}
monitor: val/MulticlassAccuracy
checkpoint_id: 8ldl6i8j
seed: 42
fold: 0
img_size: 2048
batch_size: 4
num_workers: 8
max_steps: Null
max_epochs: 50
accumulate_grad_batches: 1
lr: 2e-5
