defaults:
  - trainer: trainer_pl
  - optimizer: adamw
  - scheduler: hf_cosine_with_restarts
  - dataloader: dataloader
  - _self_

model:
  backbone: tf_efficientnetv2_s_in21ft1k
  pretrained: True
  num_classes: 5

name: ${model.backbone}
monitor: val/MulticlassAccuracy
output_dir:  ../checkpoints/${name}
img_size: 512
fold: 0
sample_size: 0
batch_size: 16
num_workers: 12
seed: 42
lr: 2e-5
max_steps: 100000
num_epochs: 1