defaults:
  - trainer: trainer_pl
  - optimizer: adam
  - scheduler: cosine_annealing
  - dataloader: dataloader
  - dataset: thumbnail
  - _self_

model:
  entrypoint: TimmModel
  backbone: tf_efficientnet_b0_ns
  pretrained: True
  num_classes: 5

augmentations:
  train:
    img_size: ${img_size}
    flip:  True
    blur: True
    dropout: True
  valid:
    img_size: ${img_size}

seed: 42
name: ${model.backbone}
output_dir:  ../checkpoints/${name}
img_size: 512
fold: 0
checkpoint_id: Null
monitor: val/MulticlassAccuracy
batch_size: 32
num_workers: 6

lr: 1e-4
max_steps: 10000
max_epochs: 20
accumulate_grad_batches: 1
