defaults:
  - trainer: trainer_pl
  - optimizer: adam
  - scheduler: cosine_annealing
  - dataloader: dataloader
  - dataframe: tile-0.25-2048-256-model
  - _self_

model:
  entrypoint: Unet 
  backbone: resnet50
  params:
    encoder_name: resnet50
    encoder_weights: imagenet
    in_channels: 3


dataset_entrypoint: VAEDataset

augmentations:
  train:
    name: get_train_transforms
    img_size: ${img_size}
    flip:  True
    blur: True
    dropout: True
  valid:
    name: get_valid_transforms
    img_size: ${img_size}

seed: 42
name: ${model.entrypoint}-${model.params.encoder_name} 
output_dir:  ../checkpoints/${name}
img_size: 256
fold: 0
checkpoint_id: Null
monitor: val/epoch_image_loss
batch_size: 64
num_workers: 10

lr: 2e-5
max_steps: 10000
max_epochs: 4
accumulate_grad_batches: 16
