imgsize: 2048
scale: 0.25
output_folder: ../input/UBC-OCEAN-PROCESSED/resized-${scale}-${imgsize}
output_name: train-resize-${scale}-${imgsize}.parquet
column_name: image_path
dataframe_path: Null
artifact_name: train_folds.parquet
num_processes: 4