imgsize: 2048
scale: 0.25
tile_size: 256
output_folder: ../input/UBC-OCEAN-PROCESSED/tile-${scale}-${imgsize}-${tile_size}
output_name: train-tile-${scale}-${imgsize}-${tile_size}.parquet
dataframe_path: Null
artifact_name: train-crop-${scale}-${imgsize}.parquet
num_processes: 10
empty_threshold: 0.0
center_crop: True